name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.3
    - name: Install dependency
      run: |
        poetry install --no-root
    - name: Run Test
      run: |
        poetry run pytest
